package Caja;

import java.math.BigDecimal;
import java.sql.*;

/** Isolated database checks; never connects to the configured shop database. */
public final class CajaServiceCheck {
    private static void check(boolean ok, String message) { if (!ok) throw new AssertionError(message); }
    private static void fails(RunnableSQL action) throws Exception {
        try { action.run(); throw new AssertionError("Operation should fail"); }
        catch (SQLException | IllegalArgumentException expected) { }
    }
    private interface RunnableSQL { void run() throws Exception; }
    private static BigDecimal money(String value) { return CajaService.importe(value); }
    public static void main(String[] args) throws Exception {
        Class.forName("org.hsqldb.jdbcDriver");
        String url = "jdbc:hsqldb:mem:caja_check";
        try (Connection c = DriverManager.getConnection(url,"sa",""); Statement s = c.createStatement()) {
            s.execute("CREATE TABLE caja_control (id INTEGER PRIMARY KEY)"); s.execute("INSERT INTO caja_control VALUES (1)");
            s.execute("CREATE TABLE caja_sesion (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, apertura TIMESTAMP DEFAULT CURRENT_TIMESTAMP, cierre TIMESTAMP, fondo DECIMAL(14,2), esperado DECIMAL(14,2), contado DECIMAL(14,2))");
            s.execute("CREATE TABLE caja_movimiento (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sesion BIGINT, fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP, tipo VARCHAR(10), medio VARCHAR(20), monto DECIMAL(14,2), detalle VARCHAR(4000), FOREIGN KEY(sesion) REFERENCES caja_sesion(id))");
        }
        CajaService service = new CajaService(() -> DriverManager.getConnection(url,"sa",""));
        check(service.estado().id==0 && !service.estado().pendiente(java.time.LocalDate.now()),"Closed box has no pending shift");
        check(money("10,50").equals(new BigDecimal("10.50")),"Decimal comma");
        fails(() -> money("-1")); fails(() -> money("1.001")); fails(() -> money("1.000,50"));
        fails(() -> service.movimiento("VENTA","Efectivo",money("10"),"No session"));
        service.abrir(money("100")); fails(() -> service.abrir(money("100")));
        CajaService.Estado estado=service.estado();
        java.time.LocalDate apertura=estado.apertura.toLocalDateTime().toLocalDate();
        check(!estado.pendiente(apertura),"Current-day shift does not warn");
        check(estado.pendiente(apertura.plusDays(1)),"Next day requires pending-close warning");
        check(estado.pendiente(apertura.plusDays(3)),"Weekend or several days pending");
        check(!estado.pendiente(apertura.minusDays(1)),"Future timestamp not treated as overdue");
        check(new CajaService(() -> DriverManager.getConnection(url,"sa","")).estado().id==estado.id,"Pending state survives service restart");
        service.movimiento("VENTA","Efectivo",money("25.50"),"Sale");
        service.movimiento("VENTA","Tarjeta",money("80"),"Card");
        service.movimiento("VENTA","Transferencia",money("60"),"Transfer");
        service.movimiento("INGRESO","Efectivo",money("20"),"Extra cash");
        service.movimiento("RETIRO","Efectivo",money("10"),"Withdrawal");
        fails(() -> service.movimiento("RETIRO","Efectivo",money("200"),"Too much"));
        fails(() -> service.movimiento("VENTA","Efectivo",money("0"),"Empty"));
        CajaService.Resumen r = service.resumen();
        check(r.efectivo.compareTo(money("135.50"))==0,"Only cash affects drawer");
        check(r.movimientos.size()==5,"Failed movements rolled back");
        check(r.ventas.get("Tarjeta").compareTo(money("80"))==0,"Card total");
        fails(() -> service.cerrar(r.id+1,money("130")));
        service.cerrar(r.id,money("130"));
        CajaService.Resumen closed = service.resumen();
        check(closed.id==0,"Closed session");
        check(service.estado().id==0,"Closing removes pending state");
        check(((BigDecimal)closed.sesiones.get(0)[6]).compareTo(money("5.50").negate())==0,"Shortage recorded");
        fails(() -> service.movimiento("VENTA","Efectivo",money("10"),"Closed"));
        service.abrir(money("50")); check(service.resumen().efectivo.compareTo(money("50"))==0,"New session independent");
        System.out.println("CajaServiceCheck OK");
    }
}
