package Caja;

import Model.Compra;
import java.math.BigDecimal;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;
import java.lang.reflect.*;

public final class HistorialVentasCheck {
    private interface Action { void run() throws Exception; }
    private static void check(boolean ok,String message) { if(!ok) throw new AssertionError(message); }
    private static void fails(Action action) throws Exception {
        try { action.run(); throw new AssertionError("Expected failure"); } catch(SQLException | IllegalArgumentException expected) { }
    }
    private static BigDecimal money(String s) { return CajaService.importe(s); }
    // The bundled HSQLDB 1.8 lacks JDBC generated-key APIs; adapt its IDENTITY()
    // only in this test. Production uses the MySQL driver's generated keys.
    private static Connection connection(String url) throws SQLException {
        Connection real=DriverManager.getConnection(url,"sa","");
        return (Connection)Proxy.newProxyInstance(HistorialVentasCheck.class.getClassLoader(),new Class<?>[]{Connection.class},(proxy,method,args) -> {
            if(method.getName().equals("prepareStatement") && args.length==2 && args[1].equals(Statement.RETURN_GENERATED_KEYS)) {
                PreparedStatement statement=real.prepareStatement((String)args[0]);
                PreparedStatement identity=real.prepareStatement("CALL IDENTITY()");
                return Proxy.newProxyInstance(HistorialVentasCheck.class.getClassLoader(),new Class<?>[]{PreparedStatement.class},(owner,operation,values) -> {
                    if(operation.getName().equals("getGeneratedKeys")) return identity.executeQuery();
                    if(operation.getName().equals("close")) identity.close();
                    try { return operation.invoke(statement,values); } catch(InvocationTargetException e) { throw e.getCause(); }
                });
            }
            try { return method.invoke(real,args); } catch(InvocationTargetException e) { throw e.getCause(); }
        });
    }
    public static void main(String[] args) throws Exception {
        Class.forName("org.hsqldb.jdbcDriver");
        String url="jdbc:hsqldb:mem:historial_check";
        try(Connection c=DriverManager.getConnection(url,"sa",""); Statement s=c.createStatement()) {
            s.execute("CREATE TABLE caja_control (id INTEGER PRIMARY KEY)"); s.execute("INSERT INTO caja_control VALUES(1)");
            s.execute("CREATE TABLE caja_sesion (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, apertura TIMESTAMP DEFAULT CURRENT_TIMESTAMP, cierre TIMESTAMP, fondo DECIMAL(14,2), esperado DECIMAL(14,2), contado DECIMAL(14,2))");
            s.execute("CREATE TABLE caja_movimiento (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, sesion BIGINT, fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP, tipo VARCHAR(10), medio VARCHAR(20), monto DECIMAL(14,2), detalle VARCHAR(4000), FOREIGN KEY(sesion) REFERENCES caja_sesion(id))");
            s.execute("CREATE TABLE venta (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, movimiento BIGINT NOT NULL, solicitud VARCHAR(36) NOT NULL, UNIQUE(movimiento), UNIQUE(solicitud), FOREIGN KEY(movimiento) REFERENCES caja_movimiento(id))");
            s.execute("CREATE TABLE venta_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, venta BIGINT, nombre VARCHAR(255), precio DECIMAL(14,2), FOREIGN KEY(venta) REFERENCES venta(id))");
            s.execute("CREATE TABLE venta_anulacion (movimiento BIGINT PRIMARY KEY, ajuste BIGINT NOT NULL, fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP, motivo VARCHAR(1000), UNIQUE(ajuste), FOREIGN KEY(movimiento) REFERENCES caja_movimiento(id), FOREIGN KEY(ajuste) REFERENCES caja_movimiento(id))");
        }
        CajaService service=new CajaService(() -> connection(url));
        List<Compra> items=Arrays.asList(new Compra("Pan","$10"),new Compra("Leche","$20.50"));
        String token=UUID.randomUUID().toString();
        fails(() -> service.cobrar(token,"Efectivo",items));
        service.abrir(money("100"));
        service.cobrar(token,"Efectivo",items); service.cobrar(token,"Efectivo",items);
        fails(() -> service.cobrar(token,"Tarjeta",items));
        service.cobrar(UUID.randomUUID().toString(),"Tarjeta",items);
        service.cobrar(UUID.randomUUID().toString(),"Transferencia",items);
        LocalDate today=LocalDate.now();
        CajaService.Historial h=service.historial(today,today,null);
        check(h.ventas.size()==3,"Retry must not duplicate sale");
        check(h.bruto.compareTo(money("91.50"))==0,"Daily gross");
        check(service.historial(today.minusDays(2),today.minusDays(1),null).ventas.isEmpty(),"Date filter");
        check(service.historial(today,today,"Tarjeta").ventas.size()==1,"Payment filter");
        long cash=service.historial(today,today,"Efectivo").ventas.get(0).id;
        CajaService.VentaRegistro v=service.detalleVenta(cash);
        check(v.items.size()==2 && v.items.get(1).getNombre().equals("Leche"),"Persistent product snapshot");
        check(v.items.get(1).getPrecio().equals("$20.50"),"Persistent ticket price");
        fails(() -> service.anular(cash," "));
        long first=service.resumen().id; service.cerrar(first,money("130.50"));
        fails(() -> service.anular(cash,"Closed"));
        service.abrir(money("10")); fails(() -> service.anular(cash,"Insufficient cash"));
        check(service.detalleVenta(cash).anulada==null,"Failed cancellation must roll back");
        service.movimiento("INGRESO","Efectivo",money("50"),"Extra cash");
        service.anular(cash,"Devolución"); fails(() -> service.anular(cash,"Duplicate"));
        check(service.resumen().efectivo.compareTo(money("29.50"))==0,"Refund in current drawer");
        check(((BigDecimal)service.resumen().sesiones.get(1)[4]).compareTo(money("130.50"))==0,"Previous closure preserved");
        v=service.detalleVenta(cash); check(v.anulada!=null && v.motivo.equals("Devolución") && v.items.size()==2,"Audit and items preserved");
        h=service.historial(today,today,null); check(h.anulado.compareTo(money("30.50"))==0,"Canceled daily amount");
        long card=service.historial(today,today,"Tarjeta").ventas.get(0).id;
        service.anular(card,"Card refund"); check(service.resumen().efectivo.compareTo(money("29.50"))==0,"Card refund does not affect cash");
        check(service.resumen().ventas.get("Tarjeta").compareTo(money("30.50").negate())==0,"Card refund adjusts current shift net");
        long transfer=service.historial(today,today,"Transferencia").ventas.get(0).id;
        try(Connection c=DriverManager.getConnection(url,"sa",""); Statement s=c.createStatement()) { s.execute("ALTER TABLE venta_anulacion ADD CONSTRAINT reject_reason CHECK (motivo <> 'Rejected')"); }
        int movements=service.resumen().movimientos.size();
        fails(() -> service.anular(transfer,"Rejected"));
        check(service.detalleVenta(transfer).anulada==null && service.resumen().movimientos.size()==movements,"Partial refund rolled back");
        service.movimiento("VENTA","Efectivo",money("5"),"Legacy sale");
        CajaService.VentaRegistro legacy=service.historial(today,today,"Efectivo").ventas.get(0);
        check(service.detalleVenta(legacy.id).items.isEmpty(),"Legacy sale is readable without inventing products");
        service.anular(legacy.id,"Legacy refund");
        service.movimiento("VENTA","Efectivo",money("30.50"),"Pan · $10\nLeche · $20.50\n");
        long anterior=service.historial(today,today,"Efectivo").ventas.get(0).id;
        CajaService.VentaRegistro recuperada=service.detalleVenta(anterior);
        check(recuperada.items.size()==2 && recuperada.items.get(1).getPrecio().equals("$20.50"),"Old receipts recover products from cash detail");
        check(service.detalleVenta(anterior).items.size()==2,"Recovery is repeatable without a new charge");
        check(CajaService.recuperarItems("Pan · $10\nLeche · $20,50\r\n",money("30.50")).size()==2,"Decimal comma and Windows lines");
        check(CajaService.recuperarItems("Oferta · $ especial · $5\n",money("5")).get(0).getNombre().equals("Oferta · $ especial"),"Separator inside product name");
        check(CajaService.recuperarItems("Pan · $10\nMissing price\n",money("10")).isEmpty(),"Partial detail must not print");
        check(CajaService.recuperarItems("Pan · $10\n",money("11")).isEmpty(),"Mismatched total must not print");
        check(CajaService.recuperarItems("Pan · $-10\n",money("10")).isEmpty(),"Invalid price must not print");
        check(CajaService.recuperarItems(null,money("10")).isEmpty(),"Missing detail must not print");
        // Failure after drawer insertion must roll back the header and movement together.
        try(Connection c=DriverManager.getConnection(url,"sa",""); Statement s=c.createStatement()) { s.execute("ALTER TABLE venta_item ADD CONSTRAINT reject_product CHECK (nombre <> 'Rejected')"); }
        int before=service.historial(today,today,null).ventas.size();
        fails(() -> service.cobrar(UUID.randomUUID().toString(),"Efectivo",Arrays.asList(new Compra("Rejected","$1"))));
        check(service.historial(today,today,null).ventas.size()==before,"Partial sale rolled back");
        CajaService.Estadisticas stats=service.estadisticas(today,today);
        check(stats.confirmadas==2 && stats.anuladas==3,"Charts exclude canceled sales and count each ticket once");
        check(stats.total.compareTo(money("61"))==0,"Charts confirmed total");
        check(stats.medios.get("Transferencia").compareTo(money("30.50"))==0 && stats.medios.get("Efectivo").compareTo(money("30.50"))==0,"Charts payment amounts");
        check(stats.productos.get("Pan").compareTo(money("20"))==0 && stats.productos.get("Leche").compareTo(money("41"))==0,"Charts combine structured products and recovered old receipts");
        check(service.estadisticas(today.minusDays(2),today.minusDays(1)).total.signum()==0,"Charts empty period");
        fails(() -> service.estadisticas(today,today.minusDays(1)));
        service.movimiento("VENTA","Efectivo",money("5"),"Old sale without product detail");
        stats=service.estadisticas(today,today);
        check(stats.productos.get("Sin detalle de productos").compareTo(money("5"))==0,"Charts include unclassified legacy sales transparently");
        BigDecimal productSum=BigDecimal.ZERO;for(BigDecimal amount:stats.productos.values())productSum=productSum.add(amount);
        check(productSum.compareTo(stats.total)==0,"Product chart reconciles with payment chart");
        System.out.println("HistorialVentasCheck OK");
    }
}
