package DataBase;

import java.sql.*;
import java.util.*;

public final class ProductosSinCodigoCheck {
    private interface Work{void run()throws Exception;}
    private static void check(boolean ok,String message){if(!ok)throw new AssertionError(message);}
    private static void fails(Work work)throws Exception{try{work.run();throw new AssertionError("Expected failure");}catch(SQLException | IllegalArgumentException expected){}}
    public static void main(String[] args)throws Exception{
        Class.forName("org.hsqldb.jdbcDriver");String url="jdbc:hsqldb:mem:sin_codigo_check";
        try(Connection c=DriverManager.getConnection(url,"sa","");Statement s=c.createStatement()){
            s.execute("CREATE TABLE producto_sin_codigo (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, nombre VARCHAR_IGNORECASE(255) NOT NULL, activo BOOLEAN DEFAULT TRUE NOT NULL, UNIQUE(nombre))");
        }
        ProductosSinCodigoService service=new ProductosSinCodigoService(() -> DriverManager.getConnection(url,"sa",""));
        check(service.listar(true).isEmpty(),"Empty catalog");
        service.guardar(null,"  Pan   casero  ");service.guardar(null,"Carnes");
        List<ProductosSinCodigoService.Entrada> rows=service.listar(true);
        check(rows.size()==2 && rows.get(0).nombre.equals("Carnes") && rows.get(1).nombre.equals("Pan casero"),"Normalized names and alphabetical order");
        long pan=rows.get(1).id;
        fails(() -> service.guardar(null,"pan casero"));fails(() -> service.guardar(null," "));fails(() -> service.guardar(null,String.join("",Collections.nCopies(256,"x"))));
        service.guardar(pan,"Pan integral");check(service.listar(true).get(1).nombre.equals("Pan integral"),"Rename without code or price");
        service.activar(pan,false);check(service.listar(true).size()==1 && service.listar(false).size()==2,"Deactivation hides quick-sale entry without deleting it");
        fails(() -> service.guardar(null,"Pan integral"));service.activar(pan,true);check(service.listar(true).size()==2,"Reactivation");
        fails(() -> service.guardar(999L,"Missing"));fails(() -> service.activar(999L,false));
        check(new ProductosSinCodigoService(() -> DriverManager.getConnection(url,"sa","")).listar(true).size()==2,"Catalog survives service restart");
        fails(() -> new ProductosSinCodigoService(() -> null).listar(true));
        System.out.println("ProductosSinCodigoCheck OK: add, rename, duplicates, validation, deactivate, reactivate and persistence");
    }
}
