-- Ejecutar una vez sobre la base existente. No modifica productos.
CREATE TABLE IF NOT EXISTS caja_control (id INT PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO caja_control (id) VALUES (1);
CREATE TABLE IF NOT EXISTS caja_sesion (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 apertura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 cierre TIMESTAMP NULL DEFAULT NULL,
 fondo DECIMAL(14,2) NOT NULL,
 esperado DECIMAL(14,2) NULL,
 contado DECIMAL(14,2) NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS caja_movimiento (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 sesion BIGINT NOT NULL,
 fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 tipo VARCHAR(10) NOT NULL,
 medio VARCHAR(20) NOT NULL,
 monto DECIMAL(14,2) NOT NULL,
 detalle TEXT NOT NULL,
 FOREIGN KEY (sesion) REFERENCES caja_sesion(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
